//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public string Id { get; set; }
        public string Bookdecision { get; set; }
        public string Bookname { get; set; }
        public string Author { get; set; }
        public string Department { get; set; }
        public string Pcdecision { get; set; }
        public Nullable<int> Pcnumber { get; set; }
        public string Problem { get; set; }
        public Nullable<int> Pcrate { get; set; }
        public string Fandecision { get; set; }
        public string Fancomment { get; set; }
        public Nullable<int> Fanrate { get; set; }
        public string Benchdecision { get; set; }
        public string Benchcomment { get; set; }
        public Nullable<int> Benchrate { get; set; }
        public string Hygienedecision { get; set; }
        public string Hygienecomment { get; set; }
        public Nullable<int> Hygienerate { get; set; }
        public Nullable<int> Overallrating { get; set; }
    }
}
