//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAccessData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoom
    {
        public string Id { get; set; }
        public Nullable<int> Class { get; set; }
        public string Projectordecision { get; set; }
        public Nullable<int> Projector { get; set; }
        public Nullable<int> Projectorscreen { get; set; }
        public string Projectorcomment { get; set; }
        public Nullable<int> Projectorrate { get; set; }
        public string Benchdecision { get; set; }
        public string Benchcomment { get; set; }
        public Nullable<int> Benchrate { get; set; }
        public string Fandecision { get; set; }
        public string Fancomment { get; set; }
        public Nullable<int> Fanrate { get; set; }
        public string Lightdecision { get; set; }
        public string Lightcomment { get; set; }
        public string Lightrate { get; set; }
        public string Hygienedecision { get; set; }
        public Nullable<int> Overallrating { get; set; }
    }
}
