//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string Student_Name { get; set; }
        public Nullable<int> Student_Rollno { get; set; }
    }
}
